[cc-switch-cli]
type = "github_release"
repo = "SaladDay/cc-switch-cli"
spec = "packages/cc-switch-cli/cc-switch-cli.spec"
copr_repos = ["ikunji/mycopr", "ikunji/cc-switch-cli"]

[maple-mono]
type = "github_release"
repo = "subframe7536/maple-font"
spec = "packages/nerd-fonts/maple-mono-nf-cn-unhinted.spec"
copr_repos = ["ikunji/mycopr", "ikunji/nerd-fonts"]

[obsidian]
type = "github_release"
repo = "obsidianmd/obsidian-releases"
spec = "packages/obsidian/obsidian.spec"
copr_repos = ["ikunji/mycopr", "ikunji/obsidian"]

[proxybridge]
type = "github_release"
repo = "InterceptSuite/ProxyBridge"
spec = "packages/proxybridge/proxybridge.spec"
copr_repos = ["ikunji/mycopr", "ikunji/proxybridge"]

[reframe]
type = "github_release"
repo = "AlynxZhou/reframe"
spec = "packages/reframe/reframe.spec"
copr_repos = ["ikunji/mycopr", "ikunji/reframe"]

[um-cli]
type = "gitea_release"
repo = "um/cli"
api_base = "https://git.um-react.app"
spec = "packages/um-cli-copr/um-cli.spec"
copr_repos = ["ikunji/mycopr", "ikunji/um-cli"]

[ge-proton]
type = "github_release"
repo = "GloriousEggroll/proton-ge-custom"
spec = "packages/ge-proton/ge-proton.spec"
copr_repos = ["ikunji/mycopr"]
transforms = { package_version = "strip_v, strip:GE-Proton, dot", proton_ver = "strip_v, strip:GE-Proton" }

[cto2api]
type = "github_commit"
repo = "wyeeeee/cto2api"
spec = "packages/cto2api/cto2api.spec"
copr_repos = ["ikunji/mycopr", "ikunji/cto2api"]

[krunner-pinyin-search]
type = "github_commit"
repo = "AOSC-Dev/krunner-pinyin-search"
spec = "packages/krunner-pinyin-search/krunner-pinyin-search.spec"
copr_repos = ["ikunji/mycopr", "ikunji/krunner-pinyin-search"]
update_changelog = true
transforms = { git_commit = "raw", git_short = "raw", commit_date = "raw" }

[zotero]
type = "aur"
repo = "zotero-bin"
spec = "packages/zotero/zotero.spec"
copr_repos = ["ikunji/mycopr"]

[rbw]
type = "github_release"
repo = "doy/rbw"
spec = "packages/rbw/rbw.spec"
copr_repos = ["ikunji/mycopr", "ikunji/rbw"]
